[package]
name = "rust-lambda-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.13.0"
aws-sdk-dynamodb = "1.63.0"
aws-config = "1.5.15"

tokio = { version = "1", features = ["macros"] }
